"""2nd db

Revision ID: 14685d0f7576
Revises: cdbb7851d297
Create Date: 2023-09-25 22:26:38.820691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14685d0f7576'
down_revision = 'cdbb7851d297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('added_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('added_date')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
